### ISSUE TITLE
Не загружается более 1 записи НОР

### ISSUE THREAD

**Issue by apridybaylo** [DirectumCompany/rx-util-importdata-net-core#18]
При загрузке нет ошибок, в файле отмечается что все загрузилось, но в системе создалась одна запись

**Comment by Pointabc** [comment]
Создал pull request для фиксации этой ошибки. https://github.com/DirectumCompany/rx-util-importdata-net-core/pull/57

**Comment by ardashev-dev** [comment]
исправлено в новой версии
