### ISSUE TITLE
В шаблоне для загрузки орг. структуры колонки Населенный пункт и Регион поменяны местами

### ISSUE THREAD

**Issue by apridybaylo** [DirectumCompany/rx-util-importdata-net-core#19]
Если указать все правильно в шаблон, то выходит ошибка что нет неправильно указан регион. Поменяв местами колонки Регион и Населеный пункт ошибка пропала

**Comment by ardashev-dev** [comment]
Добрый день, в новой версии отошли принципа порядка колонок, да сейчас уже порядок колонок не должен влиять.
