### ISSUE TITLE
Пожелание по загрузке документов

### ISSUE THREAD

**Issue by hiromant01** [DirectumCompany/rx-util-importdata-net-core#38]
Сейчас при обновлении документа, у которого есть версия выходит ошибка. Как гипотеза, это из-за того что SimpleODataClient так же пытается обновить версии документов без данных.
Предлагаю работу с версиями документов вынести в отдельный статик класс с методами расширениями, в мапинге ElectronicDocument убрать свойства с версиями, для этого создать отдельный класс только с этими свойствами.
В мапинге оставить только свойства карточка, . В таком случае карточка документа должна обновляться при повторном импорте и это не повлечет за собой переписывание кода для всех сущностей.

**Comment by ardashev-dev** [comment]
Не актуально в связи с переходом на новую версию
