### ISSUE TITLE
Доработка логирования

### ISSUE THREAD

**Issue by hiromant01** [DirectumCompany/rx-util-importdata-net-core#39]
Тут ситуация, когда ошибка валидации в прикладной RX, но в лог ошибка не записывается, что очень странно
Но читаемую ошибку можно получить из ответа СИ
catch (Exception ex)
      {
        var webEx = ex.InnerException as WebRequestException;
        if (webEx != null)
          logger.Error($"Ошибка на стороне Directum RX. Код ошибки: {webEx.Code}, Причина: {webEx.ReasonPhrase}, Ответ сервиса интеграции: {webEx.Response}");
        else
          logger.Error(ex.Message);
      }

**Comment by ardashev-dev** [comment]
Не актуально в связи с переходом на новую версию
