### ISSUE TITLE
Упростить дополнительный поиск в сущностях

### ISSUE THREAD

**Issue by R0mesh** [DirectumCompany/rx-util-importdata-net-core#65]
Уменьшить количество обращений к сервису интеграции с поиском сущностей, например тут:
src/ImportData/IntegrationServicesClient/Models/ICaseFiles.cs

`var retentionPeriod = BusinessLogic.GetEntityWithFilter<IFileRetentionPeriods>(x => x.Name == period, exceptionList, logger);`

Использовать уже имеющиеся данные, находящиеся в entity.ResultValues.

Посмотреть и по другим сущностям, где можно избавиться от повторного поиска уже найденных связанных сущностей, обращаясь к элементам сущности.

**Comment by ardashev-dev** [comment]
Закрыто в связи с переходом на новый механизм
